{{- if and (eq .Values.mode "kubeconfig") (not .Values.kubeconfig.existingSecret) -}}
{{- if not .Values.kubeconfig.data -}}
{{- fail "mode is \"kubeconfig\" but neither kubeconfig.data nor kubeconfig.existingSecret is set" -}}
{{- end -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kubagachi.kubeconfigSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubagachi.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.kubeconfig.secretKey }}: |
    {{- .Values.kubeconfig.data | nindent 4 }}
{{- end }}
